### ISSUE TITLE
iMac 2021 - M1 - 16 GB results

### ISSUE THREAD

**Issue by trozware** [SwiftPackageIndex/spi-benchmark#2]
Fastest build time: 41.2
Fastest run time: 23.4

Build:

Revision: 2.47.9
Run times: 47.07164800167084, 41.96791899204254, 42.32194399833679, 41.900104999542236, 41.61660194396973, 41.28599810600281, 41.15518295764923, 42.82579207420349, 41.88457202911377, 41.58618700504303, 41.794017910957336, 41.85750198364258, 41.725149035453796, 41.90049707889557, 41.490755915641785, 41.971883058547974, 42.16879498958588, 42.72829794883728, 43.37521493434906, 42.29733896255493

Run:
Running test: 	0 ...
Run time: 23.403
Running test: 	1 ...
Run time: 23.527
Running test: 	2 ...
Run time: 23.579
Running test: 	3 ...
Run time: 23.493
Running test: 	4 ...
Run time: 23.529
Running test: 	5 ...
Run time: 23.541
Running test: 	6 ...
Run time: 23.575
Running test: 	7 ...
Run time: 23.532

(error on run 8)

**Comment by finestructure** [comment]
Thanks for those benchmarks, Sarah!

We've seen that the tests can suffer from race conditions and fail when run in succession and you seem to have hit that snag as well. Would it be possible for you to run them perhaps in batches or 5 or so for a total number of 20 runs so they fill the whole graph? That'd be great :)

Thanks again for the PR!

**Comment by trozware** [comment]
20 results done in batches of 5:

Fastest run time: 23.29

Revision: 2.47.9
Run times: 23.292, 23.464, 23.573, 23.367, 23.604
Run times: 23.501, 23.481, 23.45, 23.541, 23.732
Run times: 23.534, 23.471, 23.477, 23.502, 23.528
Run times: 23.611, 24.769, 23.568, 23.604, 23.791

**Comment by finestructure** [comment]
Wow, I didn't even realise this at first: these are noticeably faster than all the other times! Did you get an M1 from next year? :D

Seriously, just to make sure we're comparing like-for-like: this is running the tests with a default dockerised Postgres db? Not some other PostgresDB that you might have installed?

**Comment by trozware** [comment]
Definitely. I didn't have any PostgresDB installed before this.
The build times are where I would expect from the other results, but these run times are very strange.

**Comment by finestructure** [comment]
Amazing. Thanks a lot for providing these numbers!

Can I have your machine 🤣

**Comment by trozware** [comment]
Ha ha!
My shiny yellow iMac is staying right here.

**Comment by finestructure** [comment]
Closing in favour of an issue over in the blog. Thanks again!
